### ISSUE TITLE
Move project to core 3.0 and get ERROR

### ISSUE THREAD

**Issue by TemoxaGreenMoney** [ligershark/WebOptimizer.Sass#10]
```
public void ConfigureServices(IServiceCollection services)
{
           services.AddWebOptimizer(pipeline =>
            {
                pipeline.AddScssBundle("/scss/site.min.css", "/scss/site.scss");
            });
}

public void Configure() 
{
         app.UseWebOptimizer();
         app.UseStaticFiles();
         app.UseRouting();
         app.UseEndpoints(endpoints =>
            {
                endpoints.MapDefaultControllerRoute();
            });
}
```

When run application and trying get **scss/site.min.css** crahed with error

`System.MissingMethodException: Method not found: 'Microsoft.Extensions.FileProviders.IFileProvider WebOptimizer.AssetExtensions.GetFileProvider(WebOptimizer.IAsset, Microsoft.AspNetCore.Hosting.IHostingEnvironment)'.
   at WebOptimizer.Sass.Compiler.ExecuteAsync(IAssetContext context)
   at WebOptimizer.Asset.ExecuteAsync(HttpContext context, IWebOptimizerOptions options)
   at WebOptimizer.AssetBuilder.BuildAsync(IAsset asset, HttpContext context, IWebOptimizerOptions options)
   at WebOptimizer.AssetMiddleware.HandleAssetAsync(HttpContext context, IAsset asset, WebOptimizerOptions options)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)`

and in brower get 500 error code **Not found file**

Can you help me ?

**Comment by Socratezz** [comment]
I am having the exact same issue. I think the newest version of the package needs to be released to NuGet.

**Comment by StaticBR** [comment]
This is fixed, see: #8 
I already requested a release, see: #9 
But nothing is happening :/

**Comment by TemoxaGreenMoney** [comment]
This release exists in Nuget with check "Include prerelease", but error saved (

**Comment by skimedic** [comment]
Try it now with the latest 3.x version from NuGet.

**Comment by TemoxaGreenMoney** [comment]
Thanks, i updated latest 3.x version  from Nuget and error hide !
