### ISSUE TITLE
CompileScssFiles() Throwing Exception

### ISSUE THREAD

**Issue by alexhorner** [ligershark/WebOptimizer.Sass#34]
When adding the following to ConfigureServices:
```csharp
services.AddWebOptimizer(pipeline =>
{
        pipeline.CompileScssFiles();
});
```

trying to load `~/css/site.scss` throws the following exception (when accessing https://localhost/css/site.scss):

```csharp
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      System.Exception: CacheKey generation exception in WebOptimizer.Sass.Compiler processor
       ---> System.IO.FileNotFoundException: The file **/*.scss does not exist.
         at Microsoft.Extensions.FileProviders.NotFoundFileInfo.CreateReadStream()
         at WebOptimizer.Sass.Compiler.GenerateCacheKey(HttpContext context)
         at WebOptimizer.Sass.Compiler.CacheKey(HttpContext context)
         at WebOptimizer.Asset.GenerateCacheKey(HttpContext context)
         --- End of inner exception stack trace ---
         at WebOptimizer.Asset.GenerateCacheKey(HttpContext context)
         at WebOptimizer.AssetBuilder.BuildAsync(IAsset asset, HttpContext context, IWebOptimizerOptions options)
         at WebOptimizer.AssetMiddleware.HandleAssetAsync(HttpContext context, IAsset asset, WebOptimizerOptions options)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

I am able to get it working with the following (when accessing https://localhost/css/site.scss):

```csharp
services.AddWebOptimizer(pipeline =>
{
        pipeline.AddScssBundle("/css/site.scss", "css/site.scss");
 });
 ```
 
 No configuration has been added to my `appsettings.json`

**Comment by jhumphries83** [comment]
I also have this issue, I am using .NET 5.

**Comment by LucGosso** [comment]
We do got the same when we added an addon to our site ...  https://github.com/Geta/geta-notfoundhandler/issues/8

```
FileNotFoundException: The file /**/*.css does not exist.
Microsoft.Extensions.FileProviders.NotFoundFileInfo.CreateReadStream()
WebOptimizer.Asset.LoadFileContentAsync(IFileProvider fileProvider, AssetContext config, string sourceFile)
WebOptimizer.Asset.ExecuteAsync(HttpContext context, IWebOptimizerOptions options)
WebOptimizer.AssetBuilder.BuildAsync(IAsset asset, HttpContext context, IWebOptimizerOptions options)
WebOptimizer.AssetMiddleware.HandleAssetAsync(HttpContext context, IAsset asset, WebOptimizerOptions options)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**Comment by filipe-assis** [comment]
Same issue here... .NET 6 and Windows

**Comment by HybridSolutions** [comment]
Yep... same here. Any solution for this? Is this project still active?

**Comment by madskristensen** [comment]
The project takes pull requests

**Comment by alexhorner** [comment]
@madskristensen 

With all due respect

> The project takes pull requests

Is not really an acceptable response to an issue which is just over 3 months old, describing a broken feature which is core to the project's operation and documented in the readme, on a project which is specifically referenced by Microsoft's official ASP.NET documentation as a replacement to their old bundlers.

Clearly, there are 7 unique individuals, including myself, above replies and above reactions which are all experiencing this issue _and_ taken the time to reply about it. I am sure there are many others also having the issue who do not wish to or cannot reply.

The project taking pull requests doesn't make it easy to just jump into it and start working. Not many people will be familiar with the structure of the project and its codestyle. Effort must be put into debugging this and then ultimately resolving it.

---

I have now taken on this bug myself. I cannot fix it immediately because there is a further upstream issue (which I have also resolved) in the core library, however I have the full fix locally. Please see my PR on the core library for information on both the fix for that library and the fix for this one which is also accessible directly at https://github.com/alexhorner/WebOptimizer.Sass/tree/GlobalCompilerFix.

PR: https://github.com/ligershark/WebOptimizer/pull/212

**Comment by alexhorner** [comment]
With the merge of the top level issue, I will open a PR to this repo once the new package has been released to nuget

**Comment by HybridSolutions** [comment]
> The project takes pull requests

I'm not very experienced with Github and Visual Studio but I can try. Interested in a new branch (6.0) targeting .net core 6 with an updated Razor Pages sample featuring the Scss compiler?

**Comment by filipe-assis** [comment]
@alexhorner, thanks a lot. As a workaround, I've downloaded the project and commented the cachekey part that was buggy. I've just tested your commit and worked flawless.

**Comment by alexhorner** [comment]
> @alexhorner, thanks a lot. As a workaround, I've downloaded the project and commented the cachekey part that was buggy. I've just tested your commit and worked flawless.

@filipe-assis The latest package version includes the fix if you didn't want to handle it in source code form

**Comment by filipe-assis** [comment]
> > @alexhorner, thanks a lot. As a workaround, I've downloaded the project and commented the cachekey part that was buggy. I've just tested your commit and worked flawless.
> 
> @filipe-assis The latest package version includes the fix if you didn't want to handle it in source code form

I've just updated the packages... Thanks again!
