### ISSUE TITLE
Latest WebOptimizer.Core + latest WebOptimizer.Sass packages compatibility

### ISSUE THREAD

**Issue by HybridSolutions** [ligershark/WebOptimizer.Sass#37]
Installing the latest LigerShark.WebOptimizer.Core 3.0.344 and the latest LigerShark.WebOptimizer.Sass 3.0.73-beta causes an error in the `public string CacheKey(HttpContext context) => GenerateCacheKey(context);` . I believe it's some kind of difference in the Method since downgrading the LigerShark.WebOptimizer.Core 3.0.344 to version 3.0.330 solves the issue. 

Shoudn't the project file get an update to the WebOptimizer.Core version? Currently it's referencing
`<PackageReference Include="LigerShark.WebOptimizer.Core" Version="3.0.276" />`

Using .NET 6, windows.

**Comment by alexhorner** [comment]
@HybridSolutions Please could you confirm if #39 fixes this issue?

**Comment by HybridSolutions** [comment]
> @HybridSolutions Please could you confirm if #39 fixes this issue for you?

yes it fixes it. Meanwhile I noticed you have a typo in the code:

`private WebOptimazerScssOptions ` and it should be `WebOptimizerScssOptions`

It's not a big deal but it's something it should be corrected in this release.

**Comment by alexhorner** [comment]
> > @HybridSolutions Please could you confirm if #39 fixes this issue for you?
> 
> yes it fixes it. Meanwhile I noticed you have a typo in the code:
> 
> `private WebOptimazerScssOptions ` and it should be `WebOptimizerScssOptions`
> 
> It's not a big deal but it's something it should be corrected in this release.

Indeed, I noticed this typo too. I opted to not resolve it for I do not know the implications of making a class name change. That would potentially become a more breaking change than is necessary and was out of scope of my targeted fix,

This release has already been completed, so a rename of that would have to be in another release now

**Comment by HybridSolutions** [comment]
> > > @HybridSolutions Please could you confirm if #39 fixes this issue for you?
> > 
> > 
> > yes it fixes it. Meanwhile I noticed you have a typo in the code:
> > `private WebOptimazerScssOptions ` and it should be `WebOptimizerScssOptions`
> > It's not a big deal but it's something it should be corrected in this release.
> 
> Indeed, I noticed this typo too. I opted to not resolve it for I do not know the implications of making a class name change. That would potentially become a more breaking change than is necessary and was out of scope of my targeted fix,
> 
> This release has already been completed, so a rename of that would have to be in another release now

I already corrected it just by changing the filename to WebOptimizerScssOptions.cs and VS corrected all the references of the class in the project. Working perfectly. There's no issues with that operation.

**Comment by alexhorner** [comment]
> > > > @HybridSolutions Please could you confirm if #39 fixes this issue for you?
> > > 
> > > 
> > > yes it fixes it. Meanwhile I noticed you have a typo in the code:
> > > `private WebOptimazerScssOptions ` and it should be `WebOptimizerScssOptions`
> > > It's not a big deal but it's something it should be corrected in this release.
> > 
> > 
> > Indeed, I noticed this typo too. I opted to not resolve it for I do not know the implications of making a class name change. That would potentially become a more breaking change than is necessary and was out of scope of my targeted fix,
> > This release has already been completed, so a rename of that would have to be in another release now
> 
> I already corrected it just by changing the filename to WebOptimizerScssOptions.cs and VS corrected all the references of the class in the project. Working perfectly. There's no issues with that operation.

Correct, however the class is not an internal one, it is public, which means third party references to it would break. A PR wouldn't hurt, just explaining my reasoning

**Comment by HybridSolutions** [comment]
> > > > > @HybridSolutions Please could you confirm if #39 fixes this issue for you?
> > > > 
> > > > 
> > > > yes it fixes it. Meanwhile I noticed you have a typo in the code:
> > > > `private WebOptimazerScssOptions ` and it should be `WebOptimizerScssOptions`
> > > > It's not a big deal but it's something it should be corrected in this release.
> > > 
> > > 
> > > Indeed, I noticed this typo too. I opted to not resolve it for I do not know the implications of making a class name change. That would potentially become a more breaking change than is necessary and was out of scope of my targeted fix,
> > > This release has already been completed, so a rename of that would have to be in another release now
> > 
> > 
> > I already corrected it just by changing the filename to WebOptimizerScssOptions.cs and VS corrected all the references of the class in the project. Working perfectly. There's no issues with that operation.
> 
> Correct, however the class is not an internal one, it is public, which means third party references to it would break. A PR wouldn't hurt, just explaining my reasoning

Yes I agree with you. Thanks for the fix!
