### ISSUE TITLE
.NET 6

### ISSUE THREAD

**Issue by dustinlacewell** [ligershark/WebOptimizer.Sass#42]
Hi, does this library support .NET 6? Will it? Thanks.

**Comment by HybridSolutions** [comment]
> Hi, does this library support .NET 6? Will it? Thanks.

Have you tried to use it with .NET 6?
I'm using it and it works great.

**Comment by dustinlacewell** [comment]
Cool. 👍

**Comment by HybridSolutions** [comment]
I'm using it like this in a .NET 6 Razor pages + Blazor project with just Program.cs (no startup.cs):

In Program.cs
```
// ligershark WebOptimizer.Sass
    builder.Services.AddWebOptimizer(pipeline => {
        
        // Compile and bundle Base files
        // _init.scss, style.scss, components.scss require paths to be accurate to the project!
        pipeline.AddScssBundle("/css/style.bundle.css", "theme/sass/style.scss");
        pipeline.AddJavaScriptBundle("/js/scripts.bundle.js", "theme/js/components/*.js", "theme/js/app.js");

        pipeline.AddJavaScriptBundle("/js/plugins.bundle.js",
            "theme/plugins/bootstrap-multiselectsplitter/bootstrap-multiselectsplitter.js",
            "theme/plugins/bootstrap-session-timeout/dist/bootstrap-session-timeout.js",
            "theme/plugins/fslightbox/fslightbox.js",
            "theme/plugins/jquery-idletimer/idle-timer.js",
            "theme/plugins/smooth-scroll/smooth-scroll.min.js",
            "theme/plugins/toastr/toastr.min.js"
         );

        // Compile and bundle Plugin files
        pipeline.AddScssBundle("/css/plugins.bundle.css", "theme/sass/plugins.scss");

        // Compile font styles
        pipeline.AddScssBundle("/css/ecm-icon-font.css", "css/ecm-icon-font.scss");                
    });
```

My .scss files are inside "wwwroot\theme\sass" folder and my scripts inside "wwwroot\theme\js" folder.

My appsettings.json (Disk cache disabled only while in development!)
```
"webOptimizer": {
    "enableCaching": true,
    "enableMemoryCache": false,
    "enableDiskCache": false,
    "cacheDirectory": "/var/temp/weboptimizercache",
    "enableTagHelperBundling": true,
    "allowEmptyBundle": true
  }
```

make sure your .scss files have the correct path. To be able to analyse what's going wrong, you can replicate only the [WebOptimizer.Sass](https://github.com/ligershark/WebOptimizer.Sass) project in your solution and debug it.  It will help a lot!

**Comment by EmilAlipiev** [comment]
@HybridSolutions thanks for your reply. i have tried with simple  test project but somehow i couldnt get it working. is my appsettings.json required or optional? you can check the other issue here. i tried a simple repro https://github.com/ligershark/WebOptimizer.Sass/issues/49
