### ISSUE TITLE
Can't Make Sample Project Work

### ISSUE THREAD

**Issue by rswetnam** [ligershark/WebOptimizer.Sass#5]
Hi:
I created a Sample .Net Core 2.0 project and made the changes to StartUp as shown in the instructions as well as adding the 2 packages through Nuget.  I created sample a.scss and b.scss files.  However no /all.css file is created when I build or run the project.

Am I missing something basic?  I assumed that the compilation would happen as I ran the project as the Sass Web Optimizer was in the pipeline.  You can see my sample project at https://github.com/rswetnam/LigerShark.

Any suggestions greatly appreciated.

**Comment by zbecknell** [comment]
Yes, just one thing missing: add `app.UseWebOptimizer();` to your `Configure` method before `app.UseStaticFiles()` in `Startup.cs`.

You configured WebOptimizer but never added it to your middleware pipeline.

**Comment by rswetnam** [comment]
Whoops - blush - thanks.
