### ISSUE TITLE
Display Sass Compile Errors in Browser

### ISSUE THREAD

**Issue by jamezamm** [ligershark/WebOptimizer.Sass#61]
Hi,

I am using .NET7. I am having compile errors within my sass files, but the browser only displays 500 Error. No compile errors from the sass compiler is displayed in the browser. Thus am having to solve issues by trial and error to determine which parts of my sass code is problematic.

Is there a way to display compile errors within the browser? If no, this feature needs to be introduced as tracking errors is a nightmare.

**Comment by jamezamm** [comment]
I would expect the sass compile errors to be displayed within the output of the scss/css file.

**Comment by Taritsyn** [comment]
Hello!

When I have free time, then I will try to study this problem. I just don't use it myself the WebOptimizer and I am not a member of its team.

**Comment by jamezamm** [comment]
Thanks for the reply. Thought you were the author. @madskristensen

**Comment by jamezamm** [comment]
Just found out that I can view sass compiler errors within the immediate window of visual studio.
