### ISSUE TITLE
enableTagHelperBundling=false not working for scss files

### ISSUE THREAD

**Issue by jamezamm** [ligershark/WebOptimizer.Sass#62]
Hi,

When declaring the below scss bundle
`pipe.AddScssBundle("/css/site.bundle.css",
			"/lib/jqueryui/jquery-ui.min.css",
			"/lib/bootstrap/scss/bootstrap.scss");`

then disabling enableTagHelperBundling in appsettings.json
`"enableTagHelperBundling": false`

it gets rendered as bootstrap.**css**, not bootstrap.scss
`<link href="/lib/jqueryui/jquery-ui.min.css?v=rByPlHULObEjJ6XQxW_flG2r-22R5dKiAoef-aXWfik" rel="stylesheet">`
`<link href="/lib/bootstrap/scss/bootstrap.css" rel="stylesheet">`

**Comment by jamezamm** [comment]
In my case "/lib/bootstrap/scss/bootstrap.css" does not exist, therefore the browser throws a 404 not found.

**Comment by jamezamm** [comment]
Any feedback @Taritsyn? Thanks.

**Comment by Taritsyn** [comment]
Hello!

When I have free time, then I will try to study this problem. I just don't use it myself the WebOptimizer and I am not a member of its team.

**Comment by jamezamm** [comment]
Thanks for the reply. Thought you were the author. @madskristensen

**Comment by jamezamm** [comment]
Moved this to https://github.com/ligershark/WebOptimizer/issues/264.
