### ISSUE TITLE
License link on NuGet is broken

### ISSUE THREAD

**Issue by mairaw** [ligershark/WebOptimizer.Sass#67]
Clicking on the license info link at https://www.nuget.org/packages/LigerShark.WebOptimizer.Sass takes you to https://github.com/ligershark/WebOptimizer.Sass/blob/master/LICENSE.txt, which doesn't exist

**Comment by mairaw** [comment]
License file is adde. Now only missing NuGet update.

**Comment by lahma** [comment]
The link is valid license expression, this on can be closed.
