### ISSUE TITLE
Nuget Release

### ISSUE THREAD

**Issue by StaticBR** [ligershark/WebOptimizer.Sass#9]
@madskristensen  It would be nice if you could push the newest version of this to nuget.  Thanks.

**Comment by StaticBR** [comment]
@madskristensen:  is there any good reason why you would not push an release? Or is there any timeline to release this?

**Comment by skimedic** [comment]
I'll look at it today to see if I can push it to nuget. I'm sure @Mads Kristensen<mailto:madsk@microsoft.com>  has been buried with the releases on Monday, and I'm on the road teaching, but I have a small break in my schedule today.

Regards,
Phil Japikse, MVP, ASPInsider, MCSD, MCDBA, PSM II, PSD, CSM
Consultant, Coach, Author, Teacher

________________________________

**Comment by madskristensen** [comment]
@skimedic please go ahead and release if this is ready. I'm pretty swamped atm

**Comment by skimedic** [comment]
I have released WebOptimizer.Core, WebOptimizer.Analyzers, and WebOptimizer.Sass for .NET Core 3.0. There is a branch in each project called 2.0 for ASP.NET Core 2.x.
